x-service-template: &backend-service
  build:
    context: .
    dockerfile: Dockerfile

services:
  sysintegra-services:
    <<: *backend-service
    image: sysintegra-backend

  importmuneli-services:
    <<: *backend-service
    image: importmuneli-backend

  leatsac-services:
    <<: *backend-service
    image: leatsac-backend

  ferreteria-rym-services:
    <<: *backend-service
    image: ferreteria-rym-backend

  supermarketya-services:
    <<: *backend-service
    image: supermarketya-backend

  dracoly-services:
    <<: *backend-service
    image: dracoly-backend

  masa-y-miga-services:
    <<: *backend-service
    image: masa-y-miga-backend