# Definición de un servicio base reutilizable
x-service-template: &backend-service
  # Configuración para construir la imagen del contenedor desde el contexto actual
  build:
    context: .
    dockerfile: Dockerfile
  # Configuración de redes
  networks:
    - luis
  # Configuración para reiniciar siempre el contenedor
  restart: always
  # Configuración de recursos
  deploy:
    resources:
      limits:
        cpus: "0.5"   # Máximo 50% de un núcleo
        memory: "512m" # Máximo 512MB de RAM
      reservations:
        cpus: "0.25"   # Reserva 25% de un núcleo
        memory: "256m" # Reserva 256MB de RAM

# Definición de servicios
services:
  sysintegra-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: sysintegra-backend-image
    # Nombre del contenedor
    container_name: sysintegra-backend
    # Volumen de almacenamiento
    volumes:
      - sysintegra-backend-volumen:/app/src/path

  importmuneli-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: importmuneli-backend-image
    # Nombre del contenedor
    container_name: importmuneli-backend
    # Volumen de almacenamiento
    volumes:
      - importmuneli-backend-volumen:/app/src/path

  leatsac-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: leatsac-backend-image
    # Nombre del contenedor
    container_name: leatsac-backend
    # Volumen de almacenamiento
    volumes:
      - leatsac-backend-volumen:/app/src/path
    
  ferreteria-rym-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: ferreteria-rym-backend-image
    # Nombre del contenedor
    container_name: ferreteria-rym-backend
    # Volumen de almacenamiento
    volumes:
      - ferreteria-rym-backend-volumen:/app/src/path

  supermarketya-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: supermarketya-backend-image
    # Nombre del contenedor
    container_name: supermarketya-backend
    # Volumen de almacenamiento
    volumes:
      - supermarketya-backend-volumen:/app/src/path

  dracoly-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: dracoly-backend-image
    # Nombre del contenedor
    container_name: dracoly-backend
    # Volumen de almacenamiento
    volumes:
      - dracoly-backend-volumen:/app/src/path

  main-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    <<: *backend-service
    # Nombre de la imagen de la imagen generada
    image: main-backend-image
    # Nombre del contenedor
    container_name: main-backend
    # Volumen de almacenamiento
    volumes:
      - main-backend-volumen:/app/src/path

# Definición de redes
networks:
  # Red llamada 'luis'
  luis:
    # Configuración para usar una red externa existente
    external: true

volumes:
  sysintegra-backend-volumen:
  leatsac-backend-volumen:
  ferreteria-rym-backend-volumen:
  importmuneli-backend-volumen:
  supermarketya-backend-volumen:
  dracoly-backend-volumen:
  main-backend-volumen: