# Versión de la configuración de Docker Compose
version: "3"

# Definición de servicios
services:
  sysintegra-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: sysintegra-backend-image
    # Nombre del contenedor
    container_name: sysintegra-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6001:80
    volumes:
      - sysintegra-backend-volumen:/app/src/path

  # app-bodega:
  #   # Configuración para construir la imagen del contenedor desde el contexto actual
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # Nombre de la imagen de la imagen generada
  #   image: sysintegra-backend-image
  #   # Nombre del contenedor
  #   container_name: sysintegra-backend-bodega
  #   # Configuración para reiniciar siempre el contenedor
  #   restart: always
  #   # Configuración de redes
  #   networks:
  #     - luis
  #   # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
  #   ports:
  #     - 6004:80

  # app-autopartes:
  #   # Configuración para construir la imagen del contenedor desde el contexto actual
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # Nombre de la imagen de la imagen generada
  #   image: sysintegra-backend-image
  #   # Nombre del contenedor
  #   container_name: sysintegra-backend-autopartes
  #   # Configuración para reiniciar siempre el contenedor
  #   restart: always
  #   # Configuración de redes
  #   networks:
  #     - luis
  #   # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
  #   ports:
  #     - 6007:80

  legrand-tiquepos-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: legrand-tiquepos-backend-image
    # Nombre del contenedor
    container_name: legrand-tiquepos-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6011:80
    volumes:
      - legrand-tiquepos-backend-volumen:/app/src/path

  raices-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: raices-backend-image
    # Nombre del contenedor
    container_name: raices-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6015:80
    volumes:
      - raices-backend-volumen:/app/src/path

  felicitygirls-tiquepos-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: felicitygirls-tiquepos-backend-image
    # Nombre del contenedor
    container_name: felicitygirls-tiquepos-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6019:80
    volumes:
      - felicitygirls-tiquepos-backend-volumen:/app/src/path

  bodega-modelo-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: bodega-modelo-backend-image
    # Nombre del contenedor
    container_name: bodega-modelo-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6023:80
    volumes:
      - bodega-modelo-backend-volumen:/app/src/path

  unnagro-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: unnagro-backend-image
    # Nombre del contenedor
    container_name: unnagro-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6027:80
    volumes:
      - unnagro-backend-volumen:/app/src/path

  leatsac-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: leatsac-backend-image
    # Nombre del contenedor
    container_name: leatsac-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6031:80
    volumes:
      - leatsac-backend-volumen:/app/src/path
    
  ferreteria-rym-services:
    # Configuración para construir la imagen del contenedor desde el contexto actual
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen de la imagen generada
    image: ferreteria-rym-backend-image
    # Nombre del contenedor
    container_name: ferreteria-rym-backend
    # Configuración para reiniciar siempre el contenedor
    restart: always
    # Configuración de redes
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6001 del host al puerto 80 del contenedor
    ports:
      - 6035:80
    volumes:
      - ferreteria-rym-backend-volumen:/app/src/path

# Definición de redes
networks:
  # Red llamada 'luis'
  luis:
    # Configuración para usar una red externa existente
    external: true

volumes:
  sysintegra-backend-volumen:
  legrand-tiquepos-backend-volumen:
  raices-backend-volumen:
  felicitygirls-tiquepos-backend-volumen:
  bodega-modelo-backend-volumen:
  unnagro-backend-volumen:
  leatsac-backend-volumen:
  ferreteria-rym-backend-volumen: