version: "3"

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: sysintegra-backend-image
    restart: always
    networks:
      - luis
    ports:
      - 6001:80

  app-bodega:
    extends:
      service: app-test
    ports:
      - 6002:80

  app-autopartes:
    extends:
      service: app-test
    ports:
      - 6003:80

networks:
  luis:
    external: true
