x-service-template: &backend-service
  networks:
    - luis
  restart: always

services:
  sysintegra-services:
    <<: *backend-service
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - sysintegra-backend-volumen:/app/src/path

  # importmuneli-services:
  #   image: importmuneli-backend-image
  #   container_name: importmuneli-backend
  #   volumes:
  #     - importmuneli-backend-volumen:/app/src/path

  # leatsac-services:
  #   image: leatsac-backend-image
  #   container_name: leatsac-backend
  #   volumes:
  #     - leatsac-backend-volumen:/app/src/path
    
  # ferreteria-rym-services:
  #   image: ferreteria-rym-backend-image
  #   container_name: ferreteria-rym-backend
  #   volumes:
  #     - ferreteria-rym-backend-volumen:/app/src/path

  # supermarketya-services:
  #   image: supermarketya-backend-image
  #   container_name: supermarketya-backend
  #   volumes:
  #     - supermarketya-backend-volumen:/app/src/path

  # dracoly-services:
  #   image: dracoly-backend-image
  #   container_name: dracoly-backend
  #   volumes:
  #     - dracoly-backend-volumen:/app/src/path

  # masa-y-miga-services:
  #   image: masa-y-miga-backend-image
  #   container_name: masa-y-miga-backend
  #   volumes:
  #     - masa-y-miga-backend-volumen:/app/src/path

networks:
  luis:
    external: true

volumes:
  sysintegra-backend-volumen:
  # leatsac-backend-volumen:
  # ferreteria-rym-backend-volumen:
  # importmuneli-backend-volumen:
  # supermarketya-backend-volumen:
  # dracoly-backend-volumen:
  # masa-y-miga-backend-volumen: