const MENUS = {
    DASHBOARD: 'MN0001',
    SEGURIDAD: 'MN0002',
};

const SUBMENUS = {
    PERFIL: 'SM0001',
};

const PRIVILEGIOS = {
    LISTAR_PERFIL: 'PR0001',
    CREAR_PERFIL: 'PR0002',
    EDITAR_PERFIL: 'PR0003',
    ELIMINAR_PERFIL: 'PR0004',
};

const AJUSTE_TYPES = {
    INCREMENTO: 'TA0001',
    DECREMENTO: 'TA0002',
};

const KARDEX_TYPES = {
    INGRESO: 'TK0001',
    SALIDA: 'TK0002',
};

const KARDEX_MOTIVOS = {
    ENTREDA: 'MK0001',
    AJUSTE: 'MK0002',
    SALIDA: 'MK0003',
    DEVOLUCION: 'MK0004',
};

const PRODUCT_TREATMENTS = {
    UNIDAD: 'TT0001',
    VALOR_MONETARIO: 'TT0002',
    A_GRANEL: 'TT0003',
    NINGUNO: 'TT0004',
};

const PRODUCT_TREATMENTS_DIRECT = [
    PRODUCT_TREATMENTS.UNIDAD,
    PRODUCT_TREATMENTS.A_GRANEL,
    PRODUCT_TREATMENTS.NINGUNO,
];

module.exports = {
    MENUS,
    SUBMENUS,
    PRIVILEGIOS,
    AJUSTE_TYPES,
    KARDEX_TYPES,
    KARDEX_MOTIVOS,
    PRODUCT_TREATMENTS,
    PRODUCT_TREATMENTS_DIRECT,
};
