name: Docker Image CI - SySoftIntegra BackEnd

on:
  push:
    branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    env:  
      PORT: ${{ secrets.PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      TZ: ${{ secrets.TZ }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar variables de entorno
        run: |
          check_variables() {
            for var in PORT DB_HOST DB_USER DB_PASSWORD DB_NAME DB_PORT TZ; do
              if [ -z "${!var}" ]; then
                echo "La variable de entorno $var está vacía."
              else
                echo "La variable de entorno $var contiene datos: ${!var}"
              fi
            done
          }

          check_variables

      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${PORT}"
          DB_HOST="${DB_HOST}"
          DB_USER="${DB_USER}"
          DB_PASSWORD="${DB_PASSWORD}"
          DB_NAME="${DB_NAME}"
          DB_PORT="${DB_PORT}"
          TZ="${TZ}"
          EOL

      - name: Mostrar contenido del archivo .env
        run: cat .env

      - name: Creando y ejecutando contenedor
        run: docker compose up --build -d
