name: Docker Image CI - SySoftIntegra BackEnd

on:
  push:
    branches: 
      - "master"

jobs:
  # Job para construir y desplegar la aplicación en el entorno de producción - legran tiquepos
  build-and-deploy-app-legrand-tiquepos:
    runs-on: self-hosted
    environment: legrand-tiquepos
    
    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL
    
      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build legrand-tiquepos-services -d


  # # Job para construir y desplegar la aplicación en el entorno de producción - Raices
  build-and-deploy-app-raices:
    runs-on: self-hosted
    environment: raices
    
    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL
    
      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build raices-services -d

  # Job para construir y desplegar la aplicación en el entorno de producción - Felicity
  build-and-deploy-app-felicitygirls-tiquepos:
    runs-on: self-hosted
    environment: felicitygirls-tiquepos
    
    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL
    
      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build felicitygirls-tiquepos-services -d


  # # Job para construir y desplegar la aplicación en el entorno de producción - Bodega Modelo
  # build-and-deploy-app-bodega-modelo:
  #   # Condición para ejecutar este job: cuando se hace un push a la rama 'master'
  #   runs-on: self-hosted
  #   environment: bodega-modelo
    
  #   # Variables de entorno específicas para este job
  #   env:  
  #     PORT: ${{ secrets.PORT }}
  #     APP_URL: ${{secrets.APP_URL}}
  #     DB_HOST: ${{ secrets.DB_HOST }}
  #     DB_USER: ${{ secrets.DB_USER }}
  #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     DB_NAME: ${{ secrets.DB_NAME }}
  #     DB_PORT: ${{ secrets.DB_PORT }}
  #     TZ: ${{ secrets.TZ }}
  #     ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    
  #   steps:
  #     # Paso: Checkout del código fuente
  #     - name: Checkout código
  #       uses: actions/checkout@v3
    
  #     # Paso: Crear archivo .env con las variables de entorno
  #     - name: Crear archivo .env
  #       run: |
  #         cat > .env <<EOL
  #         PORT="${{env.PORT}}"
  #         APP_URL="${{env.APP_URL}}"
  #         DB_HOST="${{env.DB_HOST}}"
  #         DB_USER="${{env.DB_USER}}"
  #         DB_PASSWORD="${{env.DB_PASSWORD}}"
  #         DB_NAME="${{env.DB_NAME}}"
  #         DB_PORT="${{env.DB_PORT}}"
  #         TZ="${{env.TZ}}"
  #         ENVIRONMENT=${{env.ENVIRONMENT}}
  #         EOL
    
  #     # Paso: Crear y ejecutar el contenedor Docker
  #     - name: Creando y ejecutando contenedor
  #       run: docker compose -f docker-compose.yml up --build bodega-modelo-services -d

  # Job para construir y desplegar la aplicación en el entorno de producción - Unnagro
  build-and-deploy-app-unnagro:
    runs-on: self-hosted
    environment: unnagro

    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL

      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build unnagro-services -d

  # Job para construir y desplegar la aplicación en el entorno de producción - Leatsac
  build-and-deploy-app-leatsac:
    runs-on: self-hosted
    environment: leatsac

    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL

      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build leatsac-services -d

  # Job para construir y desplegar la aplicación en el entorno de producción - Ferreteria rym
  build-and-deploy-app-ferreteria-rym:
    runs-on: self-hosted
    environment: ferreteria-rym
    
    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL
    
      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build ferreteria-rym-services -d

  # Job para construir y desplegar la aplicación en el entorno de producción - Ferreteria rym
  build-and-deploy-app-asiaticos-pcl:
    runs-on: self-hosted
    environment: asiaticos-pcl
    
    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
    
      - name: Crear archivo .env
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL
    
      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build asiaticos-pcl-services -d