name: Docker Staging CI - SySoftIntegra BackEnd

on:
  push:
    branches: 
      - test

jobs:
  build-and-deploy-app-test:
    runs-on: self-hosted
    environment: test

    env:  
      PORT: ${{ secrets.PORT }}
      APP_URL: ${{secrets.APP_URL}}
      APP_PDF: ${{secrets.APP_PDF}}
      APP_CPE_SUNAT: ${{secrets.APP_CPE_SUNAT}}
      APP_APIS_PERU: ${{secrets.APP_APIS_PERU}}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}

      FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
      FIREBASE_URL_PUBLIC: ${{ secrets.FIREBASE_URL_PUBLIC }}

      # VITE_APP_BACK_END: ${{ secrets.VITE_APP_BACK_END }}
      # VITE_APP_APIS_PERU: ${{ secrets.VITE_APP_APIS_PERU }}
      # VITE_APP_ENV: ${{ vars.VITE_APP_ENV }}
      # VITE_APP_VERSION: ${{ vars.VITE_APP_VERSION }}

      TZ: ${{ secrets.TZ }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # - name: Preparar frontend y definir variables de entorno
      #   run: |
      #     mkdir app
      #     git clone -b development https://github.com/luissince/syssoft-integra-frontend.git ./app
      #     cd app
      #     echo "VITE_APP_BACK_END=${{ env.VITE_APP_BACK_END }}" >> .env
      #     echo "VITE_APP_APIS_PERU=${{ env.VITE_APP_APIS_PERU }}" >> .env
      #     echo "VITE_APP_ENV=${{ env.VITE_APP_ENV }}" >> .env
      #     echo "VITE_APP_VERSION=${{ env.VITE_APP_VERSION }}" >> .env
      #     npm install
      #     source .env
      #     npm run build
    
      - name: Crear archivo .env para el backend
        run: |
          cat > .env <<EOL
          PORT="${{env.PORT}}"
          APP_URL="${{env.APP_URL}}"
          APP_PDF="${{env.APP_PDF}}"
          APP_CPE_SUNAT="${{env.APP_CPE_SUNAT}}"
          APP_APIS_PERU="${{env.APP_APIS_PERU}}"

          DB_HOST="${{env.DB_HOST}}"
          DB_USER="${{env.DB_USER}}"
          DB_PASSWORD="${{env.DB_PASSWORD}}"
          DB_NAME="${{env.DB_NAME}}"
          DB_PORT="${{env.DB_PORT}}"

          CLOUDFLARE_ACCOUNT_ID="${{env.CLOUDFLARE_ACCOUNT_ID}}"
          CLOUDFLARE_ACCESS_KEY_ID="${{env.CLOUDFLARE_ACCESS_KEY_ID}}"
          CLOUDFLARE_SECRET_ACCESS_KEY="${{env.CLOUDFLARE_SECRET_ACCESS_KEY}}"
          CLOUDFLARE_BUCKET_NAME="${{env.CLOUDFLARE_BUCKET_NAME}}"

          FIREBASE_BUCKET="${{env.FIREBASE_BUCKET}}"
          FIREBASE_URL_PUBLIC="${{env.FIREBASE_URL_PUBLIC}}"

          TZ="${{env.TZ}}"
          ENVIRONMENT=${{env.ENVIRONMENT}}
          EOL

      - name: Creando y ejecutando contenedor
        run: docker compose -f docker-compose.yml up --build sysintegra-services -d